#!/usr/bin/env bash
# Curate the Pervagans skills catalog from aitmpl (davila7/claude-code-templates).
# - copies each chosen SKILL.md (capped to whole lines under ~8KB) into the
#   backend embed dir as data/<id>.md
# - generates catalog_entries.go (ordered entry list: id, category, features)
# Source of truth: the LIST below. id|srcpath|category|featuresCSV
# srcpath "AUTHORED" => no copy (the .md is hand-written separately).
set -u
SKILLS_SRC="/c/Users/EL3ATTY/aitmpl-src/cli-tool/components/skills"
OUT="/c/Users/EL3ATTY/repos/Babbage-Ai/backend/internal/skills"
DATA="$OUT/data"
mkdir -p "$DATA"
rm -f "$DATA"/*.md 2>/dev/null

LIST='
copywriting|business-marketing/copywriting|writing|writing
content-creator|business-marketing/content-creator|writing|writing
writing-clearly|enterprise-communication/writing-clearly-and-concisely|writing|writing
content-research-writer|business-marketing/content-research-writer|writing|
copy-editing|business-marketing/copy-editing|writing|
humanizer|productivity/humanizer|writing|
seo-optimizer|business-marketing/seo-optimizer|writing|
deep-research|ai-research/deep-research|research|education
literature-review|scientific/literature-review|research|education
citation-management|scientific/citation-management|research|education
scientific-writing|scientific/scientific-writing|research|
research-lookup|scientific/research-lookup|research|
professional-translation|AUTHORED|translation|translation
localization-adaptation|AUTHORED|translation|translation
excel-analysis|enterprise-communication/excel-analysis|data|data-analysis
senior-data-scientist|development/senior-data-scientist|data|data-analysis
statistical-analysis|scientific/statistical-analysis|data|data-analysis
senior-data-engineer|development/senior-data-engineer|data|
data-scientist|ai-research/data-scientist|data|
exploratory-data-analysis|scientific/exploratory-data-analysis|data|
sql-pro|database/sql-pro|data|
marketing-strategy|business-marketing/marketing-strategy-pmm|business|business
product-strategist|business-marketing/product-strategist|business|business
pricing-strategy|business-marketing/pricing-strategy|business|business
ceo-advisor|business-marketing/ceo-advisor|business|
marketing-psychology|business-marketing/marketing-psychology|business|
launch-strategy|business-marketing/launch-strategy|business|
lead-research|business-marketing/lead-research-assistant|business|
linkedin-optimizer|career/linkedin-profile-optimizer|business|
executive-resume|career/executive-resume-writer|business|
financial-analysis|AUTHORED|finance|financial
invoice-organizer|productivity/invoice-organizer|finance|financial
market-research|scientific/market-research-reports|finance|financial
plaid-fintech|development/plaid-fintech|finance|
theme-factory|creative-design/theme-factory|design|image
ui-ux-pro-max|creative-design/ui-ux-pro-max|design|image
imagegen|creative-design/imagegen|design|image
ux-researcher|creative-design/ux-researcher-designer|design|
premium-web-design|creative-design/premium-web-design|design|
canvas-design|creative-design/canvas-design|design|
mobile-design|creative-design/mobile-design|design|
sora|video/sora|video|video
remotion|creative-design/remotion-best-practices|video|video
3d-web-experience|creative-design/3d-web-experience|video|video
manim|video/manim|video|
video-downloader|media/video-downloader|video|
clean-code|development/clean-code|development|
react-best-practices|web-development/react-best-practices|development|
api-integration|development/api-integration-specialist|development|
web-performance|web-development/web-performance-optimization|development|
senior-qa|development/senior-qa|development|
senior-devops|development/senior-devops|development|
tailwind-patterns|creative-design/tailwind-patterns|development|
code-review|development/code-review-checklist|development|
systematic-debugging|development/systematic-debugging|development|
prompt-engineering|ai-research/prompt-engineering|development|
email-composer|enterprise-communication/email-composer|communication|business
professional-communication|enterprise-communication/professional-communication|communication|
'

GO="$OUT/catalog_entries.go"
{
  echo "package skills"
  echo ""
  echo "// Code generated by aitmpl-src/curate.sh from davila7/claude-code-templates."
  echo "// DO NOT EDIT. Re-run the curation script to regenerate."
  echo "// Order here is the catalog display order; each .md lives in data/<id>.md."
  echo ""
  echo "var catalogEntries = []entry{"
} > "$GO"

copied=0; authored=0; missing=0
while IFS='|' read -r id src cat feats; do
  [ -z "${id// /}" ] && continue
  id="${id// /}"; src="${src// /}"; cat="${cat// /}"; feats="${feats// /}"
  # Go features slice literal
  if [ -z "$feats" ]; then
    gof="nil"
  else
    gof="[]string{"
    IFS=',' read -ra fa <<< "$feats"
    for f in "${fa[@]}"; do gof="$gof\"$f\", "; done
    gof="${gof%, }}"
  fi
  printf '\t{id: "%s", category: "%s", features: %s},\n' "$id" "$cat" "$gof" >> "$GO"

  if [ "$src" = "AUTHORED" ]; then
    authored=$((authored+1))
    continue
  fi
  f="$SKILLS_SRC/$src/SKILL.md"
  if [ ! -f "$f" ]; then echo "MISSING: $src" ; missing=$((missing+1)); continue; fi
  # Copy whole lines up to ~8000 bytes (keeps frontmatter + valid UTF-8 boundaries).
  awk 'BEGIN{n=0} {l=length($0)+1; if(n+l>8000) exit; print; n+=l}' "$f" > "$DATA/$id.md"
  copied=$((copied+1))
done <<< "$LIST"

echo "}" >> "$GO"
echo "copied=$copied authored=$authored missing=$missing"
echo "data files: $(ls -1 "$DATA"/*.md 2>/dev/null | wc -l)"
echo "go entries: $(grep -c '{id:' "$GO")"
