{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels: {{- include "babagemed.labels" . | nindent 4 }}
  annotations:
    {{- include "babagemed.ingressAnnotations" . | nindent 4 }}
spec:
  ingressClassName: {{ include "babagemed.ingressClass" . | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: [ {{ .Values.ingress.host | quote }} ]
      {{- if .Values.ingress.tls.existingSecret }}
      secretName: {{ .Values.ingress.tls.existingSecret | quote }}
      {{- else }}
      secretName: {{ printf "%s-tls" .Release.Name | quote }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/backend
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port: { number: {{ .Values.backend.service.port }} }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port: { number: {{ .Values.frontend.service.port }} }
{{- end -}}
